# UI
## REPL
### Warning banner
ui.repl.warning.description=Restart the REPL to apply code changes.
ui.repl.warning.restart=Restart REPL
ui.repl.warning.hideAlways=Don't show again
### Notifications
ui.repl.notification.notFound.title=Module not found
ui.repl.notification.notFound.message=REPLace could not detect the module.
### Scala
ui.repl.console.name=REPL for {0}
ui.repl.console.scala.repl=Scala REPL
ui.repl.console.welcome.shortcutMissing=SHORTCUT MISSING
ui.repl.console.welcome.autoImport.message=Auto-imported: {0}
ui.repl.console.welcome.commonText=Quick reference\n  Run code:       {0}\n  Browse history: {1} / {2}\n  Restart REPL:   {3} or the toolbar icon
ui.repl.console.welcome.noModuleText={0}\n{1}Note: This REPL session is not linked to any course module. To use a module from the REPL, select the module and press {2} to launch a new session.
ui.repl.console.welcome.fullText=Loaded A+ Courses module: {0}\n{1}\n{2}
