package fi.aalto.cs.replace.ui.base

import java.awt.event.{ActionEvent, KeyEvent, WindowAdapter, WindowEvent}
import javax.swing.JButton
import javax.swing.JComponent
import javax.swing.JDialog
import javax.swing.JPanel
import javax.swing.KeyStroke
import javax.swing.WindowConstants


/**
 * The contents of this class are fully auto-generated by the IntelliJ IDEA.
 */
class DialogBaseHelper extends JDialog {
  protected def addDefaultListeners(buttonOk: JButton, buttonCancel: JButton, contentPane: JPanel): Unit =
    buttonOk.addActionListener((e: ActionEvent) => onOk())
    buttonCancel.addActionListener((e: ActionEvent) => onCancel())
    // call onCancel() when cross is clicked
    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE)
    addWindowListener(new WindowAdapter() {
      override def windowClosing(e: WindowEvent): Unit = {
        onCancel()
      }
    })
    // call onCancel() on ESCAPE
    contentPane.registerKeyboardAction((e: ActionEvent) => onCancel(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)

  protected def onOk(): Unit =
    // add your code here
    dispose()

  protected def onCancel(): Unit =
    // add your code here if necessary
    dispose()
}